class Config:
    BASE_API_URL = "http://127.0.0.1:8082/api/v1"

    GET_ITENS_URL         = f"{BASE_API_URL}/caixa/itens/list"
    GET_CLIENTS_URL       = f"{BASE_API_URL}/caixa/client/list"
    ABRIR_CAIXA_URL       = f"{BASE_API_URL}/caixa/abrir_caixa"    
    FECHAR_CAIXA_URL      = f"{BASE_API_URL}/caixa/fechar_caixa"       
    STATUS_CAIXA_URL      = f"{BASE_API_URL}/caixa/status"  
    RECEBER_VENDA_URL     = f"{BASE_API_URL}/caixa/venda" 
    GET_ITENS_INSUMO      = f"{BASE_API_URL}/caixa/insumo"
    UPDATE_INSUMO         = f"{BASE_API_URL}/caixa/insumo/update"
    UPDATE_NOTA_CLIENTE   = f"{BASE_API_URL}/caixa/cliente/update_nota"
    GET_AGENDA_URL        = f"{BASE_API_URL}/agenda/list"
    GET_AGENDA_RESUME_URL = f"{BASE_API_URL}/agenda/resume"
    CREATE_AGENDAMENTO_URL= f"{BASE_API_URL}/agenda/create"
    DELETE_AGENDA_URL     = f"{BASE_API_URL}/agenda/delete"
    DETAIL_AGENDA_URL     = f"{BASE_API_URL}/agenda/detail"
    UPDATE_AGENDA_URL     = f"{BASE_API_URL}/agenda/update"
    CONF_AGENDA_ZAP       = f"{BASE_API_URL}/agenda/send_confirmation"  
    CREATE_ANAMENESE_URL  = f"{BASE_API_URL}/anamnese/create"
    GET_CONNECT_ZAP       = f"{BASE_API_URL}/whatsapp/connect"
    CREATE_ZAP_URL        = f"{BASE_API_URL}/whatsapp/create"
      

    CREATE_EVENT_CALENDAR_URL = "https://www.googleapis.com/calendar/v3/calendars/primary/events"