SET TERM ^ ;

ALTER TABLE LOJA ADD CONFIG_HORARIO BLOB SUB_TYPE 1 ^
ALTER TABLE CLIENTES ADD PROFISSIONAL INTEGER ^
ALTER TABLE DESPESAS ADD STATUS VARCHAR(30) ^
ALTER TABLE DESPESAS ADD ID_LOJA_EX VARCHAR(38) ^
ALTER TABLE DESC_DESPESAS ADD ID_LOJA_EX VARCHAR(38) ^
ALTER TABLE DESPESAS ADD CONSTRAINT DESPESAS_LOJA_FK FOREIGN KEY (ID_LOJA_EX) REFERENCES LOJA ^
ALTER TABLE DESC_DESPESAS ADD CONSTRAINT DESC_DESPESAS_LOJA_FK FOREIGN KEY (ID_LOJA_EX) REFERENCES LOJA ^
ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTES_PROFISSIONAIS_FK FOREIGN KEY (PROFISSIONAL) REFERENCES PROFISSIONAIS ^
COMMIT ^
SET TERM ; ^
