-- Gerado em: 2026-04-03 19:21:19
-- DEV:  127.0.0.1/base_dev
-- PROD: 100.72.176.93/base

SET TERM ^ ;

CREATE TABLE "SITE_GALERIA" (
    "ID" INTEGER NOT NULL,
    "ID_SITE" INTEGER NOT NULL,
    "URL_FOTO" VARCHAR(1000) CHARACTER SET UTF8 NOT NULL,
    "ORDEM" INTEGER
) ^

-- !! ATENÇÃO: DESPESAS.VALOR mudou de FLOAT para NUMERIC(15,2)
-- Conversão direta não suportada pelo Firebird.
-- Procedimento manual:
--   1. ALTER TABLE "DESPESAS" ADD "VALOR_NEW" NUMERIC(15,2) ^
--   2. UPDATE "DESPESAS" SET "VALOR_NEW" = "VALOR" ^
--   3. ALTER TABLE "DESPESAS" DROP "VALOR" ^
--   4. ALTER TABLE "DESPESAS" ALTER "VALOR_NEW" TO "VALOR" ^

ALTER TABLE "SITE_GALERIA" ADD CONSTRAINT "FK_GALERIA_SITE" FOREIGN KEY ("ID_SITE") REFERENCES "SITE" ("ID") ON DELETE CASCADE ^

ALTER TABLE "SITE" ADD CONSTRAINT "FK_SITE_LOJA" FOREIGN KEY ("ID_LOJA_EX") REFERENCES "LOJA" ("UUID") ^

ALTER TABLE "SITE_GALERIA" ADD CONSTRAINT "SITE_GALERIA_PK" PRIMARY KEY ("ID") ^

CREATE INDEX "IDX_GALERIA_SITE" ON "SITE_GALERIA" ("ID_SITE") ^

CREATE INDEX "IDX_SITE_LOJA" ON "SITE" ("ID_LOJA_EX") ^

CREATE OR ALTER PROCEDURE REGISTRAR_VENDA_LOTE (P_ID_PROFISSIONAL INTEGER, P_VALOR_TOTAL_VENDA NUMERIC(15,2), P_ID_CAIXA INTEGER, P_ID_CLIENTE INTEGER, P_DIN NUMERIC(15,2), P_PIX NUMERIC(15,2), P_DEB NUMERIC(15,2), P_CRD NUMERIC(15,2), P_TROCO NUMERIC(15,2), P_ID_LOJA VARCHAR(38), P_PERCENTUAL_COMISSAO NUMERIC(15,2), P_LISTA_ITENS BLOB SUB_TYPE 0)
RETURNS (R_ID_VENDA INTEGER)
AS
DECLARE VARIABLE ID_VENDA_GERADO INTEGER;
    DECLARE VARIABLE V_ITEM_ATUAL VARCHAR(1000);
    DECLARE VARIABLE V_RESTO_LISTA BLOB SUB_TYPE TEXT;
    DECLARE VARIABLE V_POS_PIPE INTEGER;
    DECLARE VARIABLE V_POS_PONTO_VIRGULA INTEGER;
    
    /* Variáveis dos Dados do Item */
    DECLARE VARIABLE V_DADO_TEMP VARCHAR(100);
    DECLARE VARIABLE J_ID_PRODUTO INTEGER;
    DECLARE VARIABLE J_QUANTIDADE INTEGER;
    DECLARE VARIABLE J_VALOR_UNIT DECIMAL(15,2);
    DECLARE VARIABLE J_VALOR_TOTAL DECIMAL(15,2);
    DECLARE VARIABLE J_COMISSIONADO VARCHAR(10);
    DECLARE VARIABLE J_IDENT_SERV INTEGER;
    
    /* Variáveis de Cálculo */
    DECLARE VARIABLE V_VALOR_COMISSAO DECIMAL(15,2);
    DECLARE VARIABLE V_VALOR_LIQUIDO DECIMAL(15,2);
BEGIN
    INSERT INTO VENDA (
        ID_PROFISSIONAL, VALOR, STATUS, DATA_VENDA, 
        ID_CAIXA, DIN, PIX, DEB, CRED, TROCO, ID_LOJA_EX, ID_CLIENTE
    )
    VALUES (
        :P_ID_PROFISSIONAL, :P_VALOR_TOTAL_VENDA, 'F', CURRENT_TIMESTAMP, 
        :P_ID_CAIXA, :P_DIN, :P_PIX, :P_DEB, :P_CRD, :P_TROCO, :P_ID_LOJA, :P_ID_CLIENTE
    )
    RETURNING ID INTO :ID_VENDA_GERADO;
    
    R_ID_VENDA = ID_VENDA_GERADO; 

    UPDATE CLIENTES SET V_GASTO = COALESCE(V_GASTO,0) + :P_VALOR_TOTAL_VENDA, DATA_ULTIMA_COMPRA = CURRENT_TIMESTAMP, PROFISSIONAL = :P_ID_PROFISSIONAL WHERE ID = :P_ID_CLIENTE;
    UPDATE PROFISSIONAIS SET V_VENDIDO = COALESCE(V_VENDIDO,0) + :P_VALOR_TOTAL_VENDA WHERE ID = :P_ID_PROFISSIONAL;

    V_RESTO_LISTA = P_LISTA_ITENS;
    
    WHILE (V_RESTO_LISTA <> '' AND V_RESTO_LISTA IS NOT NULL) DO
    BEGIN
        V_POS_PIPE = POSITION('|', V_RESTO_LISTA);
        
        IF (V_POS_PIPE > 0) THEN
        BEGIN
            V_ITEM_ATUAL = SUBSTRING(V_RESTO_LISTA FROM 1 FOR V_POS_PIPE - 1);
            V_RESTO_LISTA = SUBSTRING(V_RESTO_LISTA FROM V_POS_PIPE + 1);
        END
        ELSE
        BEGIN
            V_ITEM_ATUAL = V_RESTO_LISTA;
            V_RESTO_LISTA = ''; /* Acabou */
        END

        
        /* 1. ID PRODUTO */
        V_POS_PONTO_VIRGULA = POSITION(';', V_ITEM_ATUAL);
        J_ID_PRODUTO = CAST(SUBSTRING(V_ITEM_ATUAL FROM 1 FOR V_POS_PONTO_VIRGULA - 1) AS INTEGER);
        V_ITEM_ATUAL = SUBSTRING(V_ITEM_ATUAL FROM V_POS_PONTO_VIRGULA + 1);
        
        /* 2. QUANTIDADE */
        V_POS_PONTO_VIRGULA = POSITION(';', V_ITEM_ATUAL);
        J_QUANTIDADE = CAST(SUBSTRING(V_ITEM_ATUAL FROM 1 FOR V_POS_PONTO_VIRGULA - 1) AS INTEGER);
        V_ITEM_ATUAL = SUBSTRING(V_ITEM_ATUAL FROM V_POS_PONTO_VIRGULA + 1);
        
        /* 3. VALOR UNITARIO */
        V_POS_PONTO_VIRGULA = POSITION(';', V_ITEM_ATUAL);
        J_VALOR_UNIT = CAST(SUBSTRING(V_ITEM_ATUAL FROM 1 FOR V_POS_PONTO_VIRGULA - 1) AS DECIMAL(15,2));
        V_ITEM_ATUAL = SUBSTRING(V_ITEM_ATUAL FROM V_POS_PONTO_VIRGULA + 1);

        /* 4. VALOR TOTAL */
        V_POS_PONTO_VIRGULA = POSITION(';', V_ITEM_ATUAL);
        J_VALOR_TOTAL = CAST(SUBSTRING(V_ITEM_ATUAL FROM 1 FOR V_POS_PONTO_VIRGULA - 1) AS DECIMAL(15,2));
        V_ITEM_ATUAL = SUBSTRING(V_ITEM_ATUAL FROM V_POS_PONTO_VIRGULA + 1);

        /* 5. COMISSIONADO */
        V_POS_PONTO_VIRGULA = POSITION(';', V_ITEM_ATUAL);
        J_COMISSIONADO = SUBSTRING(V_ITEM_ATUAL FROM 1 FOR V_POS_PONTO_VIRGULA - 1);
        V_ITEM_ATUAL = SUBSTRING(V_ITEM_ATUAL FROM V_POS_PONTO_VIRGULA + 1);

        J_IDENT_SERV = CAST(V_ITEM_ATUAL AS INTEGER);


        IF (J_COMISSIONADO = 'True') THEN
            V_VALOR_COMISSAO = (J_VALOR_TOTAL / 100) * P_PERCENTUAL_COMISSAO;
        ELSE
            V_VALOR_COMISSAO = 0;

        V_VALOR_LIQUIDO = J_VALOR_TOTAL - V_VALOR_COMISSAO;

        INSERT INTO VENDA_DETALHADA (
            COD_VENDA, COD_PRODUTO, QUANTIDADE, VALOR, TOTAL, 
            COMISSAO, COD_FUNC, VALOR_MENOS_COMISSAO, DATA2
        )
        VALUES (
            :ID_VENDA_GERADO, :J_ID_PRODUTO, :J_QUANTIDADE, :J_VALOR_UNIT, :J_VALOR_TOTAL,
            :V_VALOR_COMISSAO, :P_ID_PROFISSIONAL, :V_VALOR_LIQUIDO, CURRENT_TIMESTAMP
        );

        UPDATE PRODUTOS SET VENDAS = coalesce(VENDAS,0) + :J_VALOR_TOTAL WHERE ID = :J_ID_PRODUTO;

        IF (J_IDENT_SERV = 0) THEN
            UPDATE PRODUTOS SET QUANTIDADE_ESTOQUE = coalesce(QUANTIDADE_ESTOQUE,0) - :J_QUANTIDADE WHERE ID = :J_ID_PRODUTO;
            
    END 
    
    SUSPEND;
END ^

CREATE OR ALTER PROCEDURE SP_BUSCA_DADOS_CLIENTE (P_TELEFONE VARCHAR(30))
RETURNS (CLIENTE_ID INTEGER, CLIENTE_NOME VARCHAR(100), PROFISSIONAL_ID INTEGER, PROFISSIONAL_NOME VARCHAR(100), LOJA_UUID VARCHAR(38), CONFIG_HORARIO BLOB SUB_TYPE 0, AGENDA_ID INTEGER, AGENDA_DATA TIMESTAMP, AGENDA_HORA_INI VARCHAR(30), AGENDA_HORA_FIM VARCHAR(30))
AS
BEGIN
    FOR
        SELECT 
            C.ID,
            C.NOME,
            P.ID,
            P.NOME,
            P.ID_LOJA_EX,
            L.CONFIG_HORARIO,
            A.ID,
            A.DATA2,
            A.HORA_INI,
            A.HORA_FIM
        FROM CLIENTES C
        -- 1. O índice CLIENTES_TELEFONE_IDX garante um acesso inicial imediato.
        -- 2. O índice CLIENTES_PROFISSIONAIS_FK liga rapidamente ao profissional.
        LEFT JOIN PROFISSIONAIS P ON C.PROFISSIONAL = P.ID
        -- 3. O índice UNQ1_LOJA na tabela LOJA faz a junção instantânea.
        LEFT JOIN LOJA L ON P.ID_LOJA_EX = L.UUID
        -- 4. Junção com a Agenda otimizada para usar o índice IDX_DATA2:
        LEFT JOIN AGENDA A ON P.ID = A.COD_FUNC 
                          -- Compara o TIMESTAMP puro com o limite de dias sem usar CAST
                          AND A.DATA2 >= CURRENT_DATE 
                          AND A.DATA2 < DATEADD(31 DAY TO CURRENT_DATE)
                          -- Evita o COALESCE() que também pode prejudicar índices:
                          AND (A.FLAG <> 'D' OR A.FLAG IS NULL)
        WHERE C.TELEFONE = :P_TELEFONE
        INTO 
            :CLIENTE_ID,
            :CLIENTE_NOME,
            :PROFISSIONAL_ID,
            :PROFISSIONAL_NOME,
            :LOJA_UUID,
            :CONFIG_HORARIO,
            :AGENDA_ID,
            :AGENDA_DATA,
            :AGENDA_HORA_INI,
            :AGENDA_HORA_FIM
    DO
    BEGIN
        SUSPEND;
    END
END ^

CREATE OR ALTER PROCEDURE SP_DESPESAS (P_DESCRICAO VARCHAR(30), P_STATUS VARCHAR(30), P_VALOR_PARCELA NUMERIC(15,2), P_QTD_PARCELAS INTEGER, P_FORMA_PAGAMENTO VARCHAR(30), P_DATA_PRIMEIRO_VENCIMENTO TIMESTAMP, P_ID_LOJA_EX VARCHAR(38))
AS
DECLARE VARIABLE I INTEGER;
DECLARE VARIABLE V_DATA_VENCIMENTO TIMESTAMP;
DECLARE VARIABLE V_DESCRICAO_PARCELA VARCHAR(30);
BEGIN
    -- Proteção contra loop infinito ou 0
    IF (:P_QTD_PARCELAS <= 0) THEN P_QTD_PARCELAS = 1;

    I = 1;

    WHILE (I <= :P_QTD_PARCELAS) DO
    BEGIN
        -- Calcula a data: Data Inicial + (I - 1) meses
        -- Ex: Mês 1 soma 0 meses. Mês 2 soma 1 mês, etc.
        V_DATA_VENCIMENTO = DATEADD(MONTH, I - 1, :P_DATA_PRIMEIRO_VENCIMENTO);

        -- Formata o texto "1 de 12", "2 de 12"
        V_DESCRICAO_PARCELA = CAST(I AS VARCHAR(5)) || ' de ' || CAST(:P_QTD_PARCELAS AS VARCHAR(5));

        INSERT INTO DESPESAS (
            DESCRICAO,
            PARCELA,
            VALOR,           -- Insere o valor cheio passado por parâmetro
            FORMA_PAGAMENTO,
            STATUS,
            DATA_VENCIMENTO,
            ID_LOJA_EX
        ) VALUES (
            :P_DESCRICAO,
            :V_DESCRICAO_PARCELA,
            :P_VALOR_PARCELA,
            :P_FORMA_PAGAMENTO,
            :P_STATUS,
            :V_DATA_VENCIMENTO,
            :P_ID_LOJA_EX
        );

        I = I + 1;
    END
END ^

CREATE OR ALTER PROCEDURE SP_LISTAR_DESPESAS_MES (P_ID_LOJA VARCHAR(38), P_DATA_INI DATE, P_DATA_FIM DATE)
RETURNS (R_ID INTEGER, R_DESCRICAO VARCHAR(30), R_VALOR NUMERIC(15,2), R_DATA_VENCIMENTO TIMESTAMP, R_STATUS VARCHAR(30), R_PARCELA VARCHAR(30), R_TOTAL_GERAL NUMERIC(15,2), R_ORIGEM VARCHAR(20))
AS
BEGIN
    -- O 'FOR SELECT' itera sobre os resultados linha a linha
    FOR 
        SELECT 
            ID, 
            DESCRICAO, 
            VALOR, 
            DATA_VENCIMENTO, 
            STATUS, 
            PARCELA,
            
            -- Window Function: Calcula a soma de TUDO que foi filtrado abaixo
            SUM(VALOR) OVER() AS TOTAL_GERAL,
            
            -- Define a origem (Resíduo ou Mês Atual)
            IIF(DATA_VENCIMENTO < :P_DATA_INI, 'RESIDUO', 'MES_ATUAL') AS ORIGEM
            
        FROM DESPESAS
        WHERE 
            ID_LOJA_EX = :P_ID_LOJA
            AND (
                -- Caso 1: Pertence ao período solicitado (P_DATA_INI até P_DATA_FIM)
                (DATA_VENCIMENTO >= :P_DATA_INI AND DATA_VENCIMENTO < :P_DATA_FIM AND STATUS <> 'PAGO')
                
                OR
                
                -- Caso 2: É antigo (menor que P_DATA_INI) mas está ABERTO (Resíduo)
				(
                    STATUS = 'ABERTO' 
                    AND DATA_VENCIMENTO < :P_DATA_INI 
                    AND (CURRENT_DATE >= :P_DATA_INI AND CURRENT_DATE < :P_DATA_FIM)
                )
            )
        ORDER BY 
            DATA_VENCIMENTO ASC
            
        INTO 
            :R_ID, 
            :R_DESCRICAO, 
            :R_VALOR, 
            :R_DATA_VENCIMENTO, 
            :R_STATUS, 
            :R_PARCELA, 
            :R_TOTAL_GERAL, 
            :R_ORIGEM
    DO
    BEGIN
        -- Devolve a linha processada para a aplicação
        SUSPEND;
    END
END ^

CREATE OR ALTER PROCEDURE SP_RESUMO_FINANCEIRO (P_ID_LOJA VARCHAR(38))
RETURNS (R_ANO INTEGER, R_MES INTEGER, R_TOTAL_PAGO NUMERIC(15,2), R_TOTAL_A_PAGAR NUMERIC(15,2), R_TOTAL_GERAL NUMERIC(15,2))
AS
BEGIN
  -- O comando FOR executa o SELECT e joga os valores nas variáveis de saída (R_...)
  FOR 
    SELECT 
        EXTRACT(YEAR FROM DATA_VENCIMENTO),
        EXTRACT(MONTH FROM DATA_VENCIMENTO),
        
        -- Soma Condicional (IIF é nativo no FB 3.0+)
        COALESCE(SUM(IIF(STATUS = 'PAGO', VALOR, 0)), 0),
        COALESCE(SUM(IIF(STATUS = 'ABERTO', VALOR, 0)), 0),
        COALESCE(SUM(VALOR), 0)
        
    FROM DESPESAS
    WHERE 
        ID_LOJA_EX = :P_ID_LOJA
        
        -- Lógica da Janela de Datas (-12 meses e +12 meses)
        AND DATA_VENCIMENTO >= DATEADD(MONTH, -6, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))
        AND DATA_VENCIMENTO < DATEADD(MONTH, 7, DATEADD(DAY, 1 - EXTRACT(DAY FROM CURRENT_DATE), CURRENT_DATE))
        AND STATUS <> 'PAGO'
        
    GROUP BY 
        EXTRACT(YEAR FROM DATA_VENCIMENTO), 
        EXTRACT(MONTH FROM DATA_VENCIMENTO)
    ORDER BY 
        1 ASC, 2 ASC
        
    INTO 
        :R_ANO, 
        :R_MES, 
        :R_TOTAL_PAGO, 
        :R_TOTAL_A_PAGAR, 
        :R_TOTAL_GERAL
  DO
  BEGIN
    -- SUSPEND "devolve" a linha atual para o Lazarus e continua o loop
    SUSPEND;
  END
END ^

COMMIT ^
SET TERM ; ^
